### ISSUE TITLE
The value STANDARD is not supported in the `TimeClass` enum class

### ISSUE THREAD

**Issue by sreeramk28** [sornerol/chess-com-pubapi-java-wrapper#18]
# Description
The `TimeClass` enum class does not support the value `STANDARD`. `InvalidFormatException` occurs when de-serializing the JSON responses containing the `time_class` key with value `standard`.

# Wrapper version
1.4.0

# Java version
17

# Steps to reproduce the behavior:
Getting a tournament's details by using the `getTournamentByUrlId` method.

Sample code snippet:
```
import io.github.sornerol.chess.pubapi.client.TournamentClient;

TournamentClient client = new TournamentClient();

// Below line results in an exception when de-serializing the API response to `Tournament` object
Tournament tournament = client.getTournamentByUrlId("bcc-weekly-rapid-4133769");
```
Error log:
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: 
Cannot deserialize value of type `io.github.sornerol.chess.pubapi.domain.game.enums.TimeClass` from String "standard": 
not one of the values accepted for Enum class: [daily, bullet, rapid, blitz]
```
Actual API response can be viewed here: https://api.chess.com/pub/tournament/bcc-weekly-rapid-4133769

# Expected behavior
`Tournament tournament = client.getTournamentByUrlId("bcc-weekly-rapid-4133769");`
The above line should execute successfully

**Comment by sornerol** [comment]
Thank you for the bug report. I am pushing an update that adds the standard time class. You will need to update to v 1.4.1 of the API client.

**Comment by sornerol** [comment]
Fix has been pushed. Please update your dependencies to use version 1.4.1.

**Comment by sreeramk28** [comment]
Thanks a lot for the quick resolution!!
