### ISSUE TITLE
Points of players are null eventhough are present on Chess.com

### ISSUE THREAD

**Issue by jalpp** [sornerol/chess-com-pubapi-java-wrapper#29]
# Describe the bug
tournament client shows winners' points as null
# Wrapper version
Which version of the API wrapper are you using? (e.g. 1.0.0)
1.4.3
# Java version
Which version of Java are you using? (e.g. 1.8)
18
# Steps to reproduce the behavior:
List the steps needed to reproduce the behavior.
`  System.out.println(client.getTournamentFromApiUrl("https://api.chess.com/pub/tournament/1500-middlegame-sparring-position-14-unrated-2804968").toString());
`
# Expected behavior
should print player scores but said null
# Additional context

**Comment by sornerol** [comment]
For whatever reason, Chess.com doesn't return the total points earned for an entire tournament. However, you can get this information from the get tournament round endpoint (https://api.chess.com/pub/tournament/1500-middlegame-sparring-position-14-unrated-2804968/1). For arena tournaments, there should only be one round. For a swiss or round-robin, you may need to loop through all of the rounds to get a cumulative score for each player.

```java
//Primary method for getting a tournament round's data
client.getTournamentRound("1500-middlegame-sparring-position-14-unrated-2804968", 1)

//Alternative method if you only have the API URL and don't want to bother parsing out the tournament ID and round number
client.getTournamentFromApiUrl("https://api.chess.com/pub/tournament/1500-middlegame-sparring-position-14-unrated-2804968/1")
```
