### ISSUE TITLE
How to get arena/swiss player leaderboards and their points?

### ISSUE THREAD

**Issue by jalpp** [sornerol/chess-com-pubapi-java-wrapper#30]
Sorry for this, but are there any examples of how to get arena and Swiss player leaderboards and points/tiebreaks and arena points for a given arena/swiss URL? The documentation does not include examples or helper code, can you please help me with this?

thanks.

**Comment by sornerol** [comment]
Hi jalpp,
I'm not sure I fully understand your question, but I'll do my best to answer.

If you want to get results for a tournament, you will need to fetch the data for each round of the tournament. I answered how to do this in this reply to your other recent issue: https://github.com/sornerol/chess-com-pubapi-java-wrapper/issues/29#issuecomment-1702149903

For arena tournaments, there should only be a single round. For a swiss or round-robin tournament, you will need to call the tournament round method for each round of the tournament and then aggregate the data you care about within your code.

I hope this answers your question. If I've misunderstood anything, please feel free to reply with any clarifying details.
