### ISSUE TITLE
Filter puzzles by rating

### ISSUE THREAD

**Issue by jalpp** [sornerol/chess-com-pubapi-java-wrapper#7]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. This feature is not related to any problem I faced by I would like to have a endpoint to filter puzzles by ratings.

**Describe the solution you'd like**
It could be a method in daily puzzle clients that basically sends puzzles by rating, or a different endpoint that sends puzzles based on rating input

**Describe alternatives you've considered**
Right now I’m showing puzzles randomly but I feel like it be nice to show puzzles based on user’s choice.

**Additional context**
Right now I’m using the puzzle client to display puzzle images for my discord bot, some users wanted to display puzzle image based on puzzle rating so they can solve puzzles based on their chess strength.

**Comment by sornerol** [comment]
Unfortunately, Chess.com's API does not provide for any way to filter puzzles by rating. This project is a third-party wrapper for Chess.com's API, so I am not able to create any additional methods outside of the endpoints exposed by Chess.com.

You would be better off asking Chess.com directly for this type of request. If you aren't already a member of their developer community, you can join at https://www.chess.com/club/chess-com-developer-community. If Chess.com decides to add additional filtering options to the API, then I would be able to make those features available via the Java wrapper.
