### ISSUE TITLE
How to get game gifs for a user?

### ISSUE THREAD

**Issue by jalpp** [sornerol/chess-com-pubapi-java-wrapper#8]
Not really a feature but was wondering how to get latest game of a user in a gif format? Is this available via API? Or Atleast get the game url? thanks

**Comment by sornerol** [comment]
You can get a list of a player's monthly archives using PlayerClient.getMonthlyArchivesAvailableForPlayer(), then call PlayerClient.getMonthlyArchiveForPlayerFromApiUrl() using the most recent archive URL returned in the previous step to get a player's most recent games.

As far as I'm aware, Chess.com currently does not provide a public API endpoint for getting a game in GIF format.
